DSEGOG-92 DSEGOG-91 DSEGOG-90 DSEGOG-94 DSEGOG-90 DSEGOG-96 DSEGOG-97 searching for data using experiment id
ral-facilities/operationsgateway pull request #221
Opened 2023-04-06 09:02 UTC by joshuadkitenge

## Description
- Allow the experiment id to be searchable
- The experiment ID should update the to and from dates
- to and from dates should update the shot number and visa versa
- The Timeframe must be reset when an experiment ID is chosen and visa versa 
- The Experiment Id must be reset when a date is manually inputted into the to and from date input boxes 
- Add the flash animation to the other search box
- Add experiment shaded region on "to" date picker when a "from" date is selected and visa versa
- Search within experiment Timeframe using date picker and shot number (This doesn't work if you clear and retype in a date).  

## Testing instructions
- MSW mock and the test api url 

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking
closes DSEGOG-92, closes DSEGOG-91, closes DSEGOG-90, closes DSEGOG-94, closes DSEGOG-90, closes DSEGOG-96, closes DSEGOG-97

2023-04-06 09:05 UTC, joshuadkitenge commented
![experiment id](https://user-images.githubusercontent.com/83226114/230329538-8984ef58-da27-45ea-ad48-525553cf3cde.gif)

2023-04-17 09:42 UTC, joshdimanteto commented
![shaded region](https://user-images.githubusercontent.com/83226114/232446977-9acbfb92-4671-4169-bf75-1731c9253475.gif)
![date-to-shotnum](https://user-images.githubusercontent.com/83226114/232446992-97ae151a-3d71-4f83-ab9f-f844de0b201f.gif)

2023-04-26 13:56 UTC, joshuadkitenge commented
![experiment id search functionailty](https://user-images.githubusercontent.com/83226114/234598361-248485d9-c7a5-4486-86b0-3286329219dc.gif)

2023-05-09 09:54 UTC, louise-davies commented on src/search/components/shotNumber.component.tsx
> +      (!props.searchParameterShotnumMax && !props.searchParameterShotnumMin) ||
Need to use proper `typeof x !== undefined` checks here, as these falsy checks can trigger when min and max are 0 (which are valid values but causes the flash to happen)

2023-05-15 14:33 UTC, louise-davies commented on src/search/components/shotNumber.component.tsx
> +        typeof props.changeSearchParameterShotnumMin !== undefined) ||
Can these ever be `undefined`? I thought these are functions? Previously we were doing `!props.searchParameterShotnumMax && !props.searchParameterShotnumMin`

2023-05-15 15:41 UTC, joshuadkitenge commented on src/search/components/shotNumber.component.tsx
> +        typeof props.changeSearchParameterShotnumMin !== undefined) ||
Sorry, that's my mistake. I meant to put `props.searchParameterShotnumMax` and `props.searchParameterShotnumMin`.

2023-05-16 08:10 UTC, joshuadkitenge commented on src/search/components/shotNumber.component.tsx
> +        typeof props.changeSearchParameterShotnumMin !== undefined) ||
I have fix it in the latest commit. I also noticed the logic was wrong as well  and I fix that as well.

2023-05-16 09:51 UTC, louise-davies requested changes
I found a bug when testing the shotnumber range, and noticed some inconsistent behaviour. It clears the experiment ID the first time but if I repeat the steps then it doesn't clear it. Looking at the range I see that it is in range of the experiment and so should not clear. Perhaps because the value returned from range converter isn't defined on the first attempt and so experiment ID clears before it's fetched, but next time it's already fetched and so it doesn't clear? See GIF

![OG-experiment-bug](https://github.com/ral-facilities/operationsgateway/assets/22525471/27d1eeeb-d910-40fc-a331-83f1a95cc249)

2023-05-16 15:47 UTC, joshuadkitenge commented
> I found a bug when testing the shotnumber range, and noticed some inconsistent behaviour. It clears the experiment ID the first time but if I repeat the steps then it doesn't clear it. Looking at the range I see that it is in range of the experiment and so should not clear. Perhaps because the value returned from range converter isn't defined on the first attempt and so experiment ID clears before it's fetched, but next time it's already fetched and so it doesn't clear? See GIF
> 
> ![OG-experiment-bug](https://user-images.githubusercontent.com/22525471/238606010-27d1eeeb-d910-40fc-a331-83f1a95cc249.gif)

Addressed in [514a1b8](https://github.com/ral-facilities/operationsgateway/pull/221/commits/514a1b86b70d88b144888d89f56f579efdee1fe9)

- The problem occurred because I wasn't using the dates received from the range convertor directly

2023-05-16 15:58 UTC, joshuadkitenge commented
![exper-id](https://github.com/ral-facilities/operationsgateway/assets/83226114/4e9cade3-9cde-4909-bbdc-49bb364e9698)

2023-05-16 18:23 UTC, joshuadkitenge commented
![exper-id-2](https://github.com/ral-facilities/operationsgateway/assets/83226114/7cd5027d-a74e-42e4-ba52-5c80b27caf6d)

In the GIF above. I noticed that the date range animation wasn't triggering the second time around. I have addressed this in  [55f2361](https://github.com/ral-facilities/operationsgateway/pull/221/commits/55f2361a4fc20e4af99563d0bba25ad06b70dc8f)

2023-05-25 08:48 UTC, louise-davies approved these changes
The fixes you added look good, and playing around a little more reveals no further bugs that I can see so LGTM

2023-05-25 09:01 UTC, merged