Add an auto refresh toggle when relative timeframe is set
ral-facilities/operationsgateway pull request #222
Opened 2023-04-13 14:50 UTC by kennethnym

## Description
This PR adds a toggle next to the refresh button that allows users to enable auto refresh of data when a relative time frame is set, e.g. "last 10 minutes".

I set the auto refresh to happen every minute, but happy to change it if needed.

## Testing instructions

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking
connect to DSEGOG-86

2023-04-19 08:54 UTC, louise-davies requested changes
Code looks good, however when a user first loads up the app, the first time they select a relative timeframe the auto refresh toggle quickly flashes into view then away again. See GIF

![OG-auto-refresh](https://user-images.githubusercontent.com/22525471/233022383-4d4f2432-4d84-4dd5-abcc-eb25c09f3d55.gif)

Could you investigate this please? Also, I believe that the auto-refresh toggle should have the same "behaviour" as the refresh button itself - either both the buttom and the toggle should be hidden when a non-relative timeframe search is used, or both are visible but disabled. It's a bit odd to have one doing one and one doing the other. If we decide to just disable them both then that fies the issue in the GIF, but I wouldn't mind hiding them both if the GIF issue is fixed.

2023-04-19 09:38 UTC, kennethnym commented
I think I know why it is happening - the toggle's appearance depends on `timeframeRange` & `paramsUpdated`. When the user selects a time frame, `timeframeRange` is set immediately, but `paramsUpdated` at that time is still `false`, so the toggle briefly appears, then `paramsUpdated` is correctly updated in a `useEffect`, which then hides the toggle.

2023-05-09 12:02 UTC, louise-davies approved these changes
LGTM

2023-05-09 12:36 UTC, louise-davies approved these changes
LGTM

2023-05-09 13:04 UTC, merged