DSEGOG-129 save sessions
ral-facilities/operationsgateway pull request #249
Opened 2023-05-30 08:55 UTC by joshuadkitenge

## Description
Enter a description of the changes here

## Testing instructions
Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking
closes DSEGOG-129

2023-06-13 12:59 UTC, joshuadkitenge commented
![save-session-1](https://github.com/ral-facilities/operationsgateway/assets/83226114/c14a7a0f-c6b0-4560-ab48-1a58809bbd31)

2023-06-28 14:34 UTC, joshuadkitenge commented
![add save session](https://github.com/ral-facilities/operationsgateway/assets/83226114/06ae6fb9-d1b9-4d6e-a6ab-ee610d2cb589)

2023-08-03 12:39 UTC, louise-davies commented on src/session/saveSessionDialogue.component.tsx
> +          label="Name*"
Minor point - but the `*` shouldn't be added to the `label` - instead add the `required` prop to the `TextField` - this adds the `*` automatically without then messing up accessibility (i.e. the * is marked with aria-hidden so screen readers ignore it, etc.)

2023-08-03 12:43 UTC, louise-davies requested changes
Looks fine other than one comment I had re: a text field.

2023-08-03 14:15 UTC, louise-davies approved these changes
LGTM

2023-08-03 14:22 UTC, merged