Data export
ral-facilities/operationsgateway pull request #364
Opened 2024-03-01 12:00 UTC by kaperoo

## Description
Enter a description of the changes here

## Testing instructions
Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking
connect to DSEGOG-119

2024-06-03 09:10 UTC, louise-davies requested changes
Overall looking good - just found 1 bug to do with Unlimited shots and various code style comments.

Another comment is that if the export request takes a long time - there's no visual to the user that the request is processing. Perhaps we can use a [LoadingButton](https://mui.com/material-ui/react-button/#loading-button)? Would also need to disable clicking away from the export dialogue when fetching as well... Alternatively, eCat has a "generating data" overlay which we could also do with a [Backdrop](https://mui.com/material-ui/react-backdrop/)

![image](https://github.com/ral-facilities/operationsgateway/assets/22525471/fe670b83-e3e3-44e7-af75-bb5b4121c635)

2024-06-03 09:10 UTC, louise-davies commented on cypress/e2e/export.cy.ts
> +  });
This can be one "can open and close the dialog" test since the first test case is covered in the latter anyway

2024-06-03 09:10 UTC, louise-davies commented on src/api/export.tsx
> +            : 0;
This logic doesn't work when maxShots is Unlimited i.e. the value of `maxShots` is `Infinity` - the backend doesn't like `Infinity` as a value. We should probably not set `offsetParams` at all in that case

2024-06-03 09:10 UTC, louise-davies commented on src/api/export.tsx
> +            : 0;
We should also probably have a test case to cover Unlimited shots since handling with `Infinity` is weirder than the difference between 50 and 1000

2024-06-03 09:10 UTC, louise-davies commented on src/export/exportButton.component.test.tsx
> +  });
This test seems to be covered by the previous test case

2024-06-03 09:10 UTC, louise-davies commented on src/export/exportButton.component.test.tsx
> +    fireEvent.click(screen.getByText('Export'));
Is there a reason `fireEvent` is needed here over `userEvent`?

2024-06-03 09:10 UTC, louise-davies commented on src/export/exportDialogue.component.tsx
> +  const mutate = useExportData().mutate;
Style-wise, I think `const { mutate } = useExportData();` looks better, plus is more extensible if we ever need other variables from `useExportData`

2024-06-03 09:10 UTC, louise-davies commented on src/export/exportDialogue.component.tsx
> +  }, [onClose]);
This wrapper function isn't needed as `handleClose` as the exact same call signature as `onClose` - just pass `onClose` directly where you pass `handleClose`

2024-06-03 09:10 UTC, louise-davies commented on src/views/recordTable.component.test.tsx
> +      );
Why is this necessary? I get in the previous test we're reducing the number of results to make asserting all rows selected easier, but since in this test we're just indexing individual rows I would guess the test works fine without this

2024-06-05 13:39 UTC, kaperoo commented
Addressed comments, added a _"generating export data"_ backdrop and fixed the default timestamp sorting issue.

|Backdrop in light mode:|Backdrop in dark mode:|
|:-------------------------:|:-------------------------:|
|<img width="250" alt="light" src="https://github.com/ral-facilities/operationsgateway/assets/72079517/f4025b7b-83e1-4177-8248-310cb1332cf5">|<img width="250" alt="dark" src="https://github.com/ral-facilities/operationsgateway/assets/72079517/5b2f7986-a846-4761-b11d-03730a0be6d5">|

2024-06-11 13:11 UTC, louise-davies approved these changes
Seems to be working well - all rows export is working with Unlimited shots mode and the loading dialogue looks good :)

2024-06-11 14:59 UTC, merged