DSEGOF-333 Remove yarn PnP
ral-facilities/operationsgateway pull request #377
Opened 2024-07-11 08:58 UTC by joelvdavies

## Description
Removes yarn PnP in preparation for Vite. Based on #375 to avoid conflicts.

## Testing instructions
Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage

## Agile board tracking
Closes DSEGOG-333

2024-07-12 13:52 UTC, joshuadkitenge requested changes
Works well, Just one minor comment.

Can the .gitignore be updated please 
https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored

2024-07-12 13:59 UTC, joelvdavies commented
> Works well, Just one minor comment.
> 
> Can the .gitignore be updated please https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored

Yeah, I was in two minds as both worked just fine, and we didn't use it on IMS either, but I think its best to use theirs exactly so just updated both.

2024-07-12 14:12 UTC, joshuadkitenge approved these changes, later dismissed

2024-07-15 13:02 UTC, louise-davies approved these changes
LGTM

2024-07-15 13:04 UTC, joshuadkitenge approved these changes

2024-07-15 13:09 UTC, merged